DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Location;
drop table if exists joiner;
DROP TABLE IF EXISTS saved;


DROP INDEX IF EXISTS uniemail;
DROP INDEX IF EXISTS unistuid;